---
# file: roles/developer/tasks/main.yml

- name: Install distribution - release - machine prerequisites
  package:
    name: "{{ packages | join(',') }}"
    state: latest
    update_cache: true
  tags:
    - install-dependencies

- name: Configure distribution - release - machine specifics
  include_tasks: "{{ ansible_distribution|lower }}_{{ ansible_distribution_release }}.yml"
  tags:
    - install-dependencies

- name: Install git-review
  pip:
    name: "git-review"
    executable: "pip3"
  tags:
    - install-dependencies

- name: Install Oh-My-Ssh
  become_user: "vagrant"
  raw: 'sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"'
  failed_when: False
  tags:
    - set-zsh

- name: Copy .ssh dir
  become_user: "vagrant"
  copy:
    src: "files/ssh/"
    dest: "/home/vagrant/.ssh/"
    owner: "vagrant"
    group: "vagrant"
    mode: 0600
  tags:
    - set-keys

- name: Copy .irssi dir
  become_user: "vagrant"
  copy:
    src: "files/.irssi/"
    dest: "/home/vagrant/.irssi/"
    owner: "vagrant"
    group: "vagrant"
    mode: 0644
  tags:
    - set-irssi

- name: Copy .tmux.conf file
  become_user: "vagrant"
  template:
    src: "files/.tmux.conf"
    dest: "/home/vagrant/"
    owner: "vagrant"
    group: "vagrant"
    mode: 0644
  tags:
    - set-tmux

- name: Clone Tmux-tpm repo
  become_user: "vagrant"
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "/home/vagrant/.tmux/plugins/tpm"
    accept_hostkey: yes
  tags:
    - set-tmux

- name: Clone Tmux-powerline repo
  become_user: "vagrant"
  git:
    repo: "https://github.com/erikw/tmux-powerline.git"
    dest: "/home/vagrant/.tmux/plugins/tmux-powerline"
    accept_hostkey: yes
  tags:
    - set-tmux

- name: Install powerline
  pip:
    name: "git+git://github.com/Lokaltog/powerline"
    executable: "pip3"
  tags:
    - set-tmux

- name: Copy .vimrc file
  become_user: "vagrant"
  template:
    src: "files/.vimrc"
    dest: "/home/vagrant/"
    owner: "vagrant"
    group: "vagrant"
    mode: 0644
  tags:
    - set-vim

- name: Clone VundleVim repo
  become_user: "vagrant"
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "/home/vagrant/.vim/bundle/Vundle.vim"
    accept_hostkey: yes
  tags:
    - set-vim

- name: Clone Nerd-fonts repo
  become_user: "vagrant"
  git:
    repo: "https://github.com/ryanoasis/nerd-fonts"
    dest: "/home/vagrant/nerd-fonts"
    depth: 1
    accept_hostkey: yes
  tags:
    - set-fonts

- name: Install nerd-fonts
  raw: "/home/vagrant/nerd-fonts/install.sh"
  tags:
    - set-fonts

- name: Update font-cache
  raw: "fc-cache -vf"
  tags:
    - set-fonts
