---
# file: roles/common/tasks/fedora_.yml

- name: Enable cockpit service
  systemd:
    name: "cockpit.socket"
    state: "started"
    enabled: "yes"
    masked: "no"
  tags:
    - install-dependencies

- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: "targeted"
    state: "permissive"
  tags:
    - install-dependencies

