---
# file: roles/common/tasks/main.yml

- name: Set hostname
  hostname:
      name: "{{ hostname }}"
  tags:
    - set-hostname

- name: Install distribution - release - machine prerequisites
  package:
    name: "{{ packages | join(',') }}"
    state: latest
    update_cache: true
  tags:
    - install-dependencies

- name: Configure distribution - release - machine specifics
  include_tasks: "{{ ansible_distribution|lower }}_{{ ansible_distribution_release }}.yml"
  tags:
    - install-dependencies

- name: Allow passwordless sudo for vagrant user
  lineinfile:
    path: "/etc/sudoers.d/vagrant"
    line: "vagrant ALL=(ALL) NOPASSWD:ALL"
    create: yes
  tags:
    - set-users
