---
# file: roles/common/defaults/main.yml

packages: "{{ packages_base + packages_by_distro[ansible_distribution|lower] }}"

packages_base:
  - "tree"
  - "tmux"
  - "vim"
  - "wget"
  - "xsel"

packages_by_distro:
  fedora:
    - "cockpit"
  ubuntu:
    - "darktable"
