---
# file: roles/developer/defaults/main.yml

packages: "{{ packages_base + packages_by_distro[ansible_distribution|lower] }}"

packages_base:
  - "curl"
  - "git"
  - "mc"
  - "openvpn"
  - "powerline"
  - "tree"
  - "tmux"
  - "vim"
  - "wget"
  - "xsel"
  - "zsh"

packages_by_distro:
  fedora:
    - "@Development tools"
    - "python-devel"
    - "python-pip"
    - "python-setuptools"
    - "python-virtualenv"
  ubuntu:
    - "build-essential"
    - "fontconfig"
    - "python3-dev"
    - "python3-pip"
    - "python3-virtualenv"
